Update mkcheck

diff --git a/mkcheck b/mkcheck
--- a/mkcheck
+++ b/mkcheck
@@ -15,8 +15,23 @@ UBLUE='\033[4;34m'
 URED='\033[4;31m'
 LCYN='\033[1;36m'
 Z=1
-
+function trap_ctrlc (){
+    # perform cleanup here
+    echo -e "${URED}Ctrl-C caught...${NC}"
+    echo -e "${W}Would you like to exit?${YLW}(y/n)${NC}"
+	read EXIT
+	if [[ ${EXIT} == "y" ]]; then
+		if [[ ${MODULE} == "1" ]]; then
+			apresults
+		fi
+		exit 2
+	else
+		return
+	fi
+}
+# Invoke trap_ctrlc
 trap "trap_ctrlc" 2
+## Privilige and File Checks
 sudo chown $USER:$USER -R /opt/MkCheck
 cd /opt/MkCheck
 # Root Check
@@ -129,24 +144,6 @@ running(){
 	sed -i "s/ARG/${VAR}/g" scripts/miko.py
 	echo -e "${UPURPLE}${Z}.${UBLUE}Next Target is ${YLW}${VAR}${NC}"
 }
-function trap_ctrlc (){
-    # perform cleanup here
-    echo -e "${URED}Ctrl-C caught...${NC}"
-    echo -e "${W}Would you like to exit?${YLW}(y/n)${NC}"
-	read EXIT
-	if [[ ${EXIT} == "y" ]]; then
-		if [[ ${MODULE} == "1" ]]; then
-			apresults
-		elif [[ ${MODULE} == "2" ]]; then
-			rsfresults
-		else
-			sleep 1
-		fi
-		exit 2
-	else
-		return
-	fi
-}
 # Final Results Correlation for Net AP Name
 apresults(){
 	for log in `cat /opt/MkCheck/files/tiks_res.txt`
@@ -157,20 +154,6 @@ apresults(){
 			cat results/Vulns/${SESSION}/${log}.results >> results/Vulns/${SESSION}/final.results
 			echo "==========================================================================="
 		done
-	main
-}
-# Jailbreak Result Correlation
-rsfresults(){
-	for log in `cat /opt/MkCheck/files/tiks_res.txt`
-		do
-			echo "${log}"
-			echo "${log}" >> results/RSF/${SESSION}/final.results
-			cat results/RSF/${SESSION}/${log}.results
-			cat results/RSF/${SESSION}/${log}.results >> results/RSF/${SESSION}/final.results
-			echo "==========================================================================="
-			sleep 2
-		done
-	main
 }
 # Mikro Network AP Name Check (No Proxy)
 mchecker(){
@@ -194,8 +177,8 @@ mchecker(){
 			breaks
 		fi
 	done
-
 	apresults
+	main
 }
 # Network AP Discovery (with Proxy)
 pchecker(){
@@ -219,8 +202,8 @@ pchecker(){
 			break
 		fi
 	done
-
 	apresults
+	main
 }
 # Routersploit Vuln Check
 rtsploit(){
@@ -246,10 +229,6 @@ up_arg(){
     echo $3 >> temp.log
     echo $4 >> temp.log
     echo $5 >> temp.log
-    echo $6 >> temp.log
-    echo $7 >> temp.log
-    echo $8 >> temp.log
-    echo $9 >> temp.log
 
     for UFILES in `cat temp.log`
        	        do
@@ -293,6 +272,7 @@ update(){
 }
 # MkCheck Start
 main(){
+	MODULE=''
 	echo -e "${BRED}"
 	python3 files/banner.py
 	echo -e "${ORNG}Codename: ${LCYN}JailBoxer"
@@ -313,7 +293,7 @@ main(){
 		echo -e "${W}Would you like to run MCheck using a proxy?${YLW}(y/n)${NC}"
 		read PROXY
 		if [[ ${PROXY} == "y" ]]; then
-			sudo service tor start
+			sudo service tor restart
 			pchecker
 		else
 			mchecker
